stages:
  - build
  - build pdf
  - deploy

variables:
  GIT_DEPTH: "1"

.yarn:
  image: node:12
  before_script:
    - yarn install --production
    - export PATH="$PATH:$PWD/node_modules/.bin"

.generate:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - public/
      - db.json
  artifacts:
    expire_in: 1 week

.docker:
  variables:
    DOCKER_USERNAME: wi1dcard
    DOCKER_IMAGE: $DOCKER_USERNAME/blog
    DOCKER_TAG: build-$CI_PIPELINE_ID
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  before_script:
    - apk add make
    - docker info

.deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: on_success
    - when: manual

optimize images:
  extends: [.yarn, .generate]
  stage: build
  script:
    - build/optimize-images.sh
  artifacts:
    paths:
      - public/resources/

build html:
  extends: [.yarn, .generate]
  stage: build
  script:
    - make lint
    - hexo generate
  artifacts:
    paths:
      - public/

build pdf:
  extends: [.docker, .generate]
  stage: build pdf
  script:
    - make validate-pdf || make pdf
  artifacts:
    paths:
      - public/resume/wi1dcard.pdf

publish image:
  extends: .docker
  stage: deploy
  script:
    - make image
    - make image-push

.deploy_ssh:
  extends: .deploy
  image: registry.gitlab.com/wi1dcard/docker-ssh-client:master
  before_script:
    - eval $(ssh-agent -s)
    - echo -n "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh

deploy vm:
  extends: .deploy_ssh
  variables:
    RSYNC_HOST: wi1dcard.dev
  script:
    - apk add rsync
    - ssh-keyscan -H "$RSYNC_HOST" >> ~/.ssh/known_hosts
    - rsync -vh -rtz --delete "./public/" "$RSYNC_USER@$RSYNC_HOST:$RSYNC_DEST"
    - ssh "$RSYNC_USER@$RSYNC_HOST" "chmod -R a+rX '$RSYNC_DEST'"

mirror to github:
  extends: .deploy_ssh
  # allow_failure: true
  stage: build
  variables:
    GIT_DEPTH: "0"
    # GIT_STRATEGY: clone
  script:
    - apk add git git-lfs
    - ssh-keyscan -H "github.com" >> ~/.ssh/known_hosts
    - git checkout -b master
    - git remote add github git@github.com:wi1dcard/blog.git
    - git fetch --all
    - git config --local lfs.https://github.com/.locksverify false
    - git push -f github master
