stages:
  - build html
  - build pdf
  - build image
  - deploy

variables:
  GIT_DEPTH: "1"
  DOCKER_USERNAME: wi1dcard
  DOCKER_IMAGE: $DOCKER_USERNAME/blog
  DOCKER_TAG: build-$CI_PIPELINE_ID

default:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - public/resources/

.yarn:
  image: node:12
  before_script:
    - yarn install --production
    - export PATH="$PATH:$PWD/node_modules/.bin"

.docker:
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  before_script:
    - apk add make
    - docker info

.deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: on_success
    - when: manual

optimize images:
  extends: .yarn
  stage: build html
  script:
    - build/optimize-images.sh
  artifacts:
    paths:
      - public/resources/
    expire_in: 1 week

build html:
  extends: .yarn
  stage: build html
  script:
    - build/lint-categories.sh
    - lint-md source/_posts --config build/lint-md.json
    - hexo generate
  artifacts:
    paths:
      - public/
    expire_in: 1 week

build pdf:
  extends: .docker
  stage: build pdf
  script:
    - make pdf
  dependencies:
    - build html
  artifacts:
    paths:
      - public/resume/wi1dcard.pdf
    expire_in: 1 week

build image:
  extends: .docker
  stage: build image
  script:
    - make image
    - make image-push

deploy vm:
  extends: .deploy
  image: alpine
  variables:
    RSYNC_HOST: wi1dcard.dev
  before_script:
    - apk add rsync openssh-client
  script:
    - eval $(ssh-agent -s)
    - echo -n "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -H "$RSYNC_HOST" >> ~/.ssh/known_hosts
    - rsync -vh -rtz --delete "./public/" "$RSYNC_USER@$RSYNC_HOST:$RSYNC_DEST"
