stages:
  - build
  - build pdf
  - publish
  - deploy

variables:
  GIT_DEPTH: "1"

.yarn:
  image: node:12
  before_script:
    - yarn install --production
    - export PATH="$PATH:$PWD/node_modules/.bin"

.generate:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - public/
  artifacts:
    expire_in: 1 week

.docker:
  variables:
    DOCKER_USERNAME: wi1dcard
    DOCKER_IMAGE: $DOCKER_USERNAME/blog
    DOCKER_TAG: build-$CI_PIPELINE_ID
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  before_script:
    - apk add make
    - docker info

.deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: on_success
    - if: '$CI_COMMIT_REF_NAME != "master" && $CI_PIPELINE_SOURCE == "push"'
      when: manual

optimize images:
  extends: [.yarn, .generate]
  stage: build
  script:
    - build/optimize-images.sh
  artifacts:
    paths:
      - public/resources/

build html:
  extends: [.yarn, .generate]
  stage: build
  script:
    - make lint
    - make html
  artifacts:
    paths:
      - public/

build pdf:
  extends: [.docker, .generate]
  stage: build pdf
  script:
    - make resume-pdf
  artifacts:
    paths:
      - public/resume/Weizhe-Sun-Resume.pdf

publish image:
  extends: .docker
  stage: publish
  script:
    - make image
    - make image-tls
    - make image-push

deploy vm:
  extends: .deploy
  tags: [server]
  dependencies: []
  script:
    - cd deploy/
    - docker-compose pull
    - docker-compose -p blog up -d --remove-orphans --force-recreate

mirror to github:
  image: wi1dcard/ssh-client:master
  stage: build
  variables:
    GIT_DEPTH: "0"
    # GIT_STRATEGY: clone
  only:
    - master
  before_script:
    ## SSH
    - eval $(ssh-agent -s)
    - echo -n "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    ## Git
    - apk add git git-lfs
    - ssh-keyscan -H "github.com" >> ~/.ssh/known_hosts
  script:
    - git checkout -b master
    - git remote add github git@github.com:wi1dcard/blog.git
    - git fetch --all
    - git lfs fetch --all
    - git config --local lfs.https://github.com/.locksverify false
    - git push -f github master
