dist: bionic
language: node_js
node_js: [ "12" ]
services: [ docker ]

cache:
  yarn: true

git:
  depth: 1

env:
  global:
    - DOCKER_USERNAME=wi1dcard
    - DOCKER_IMAGE=$DOCKER_USERNAME/blog
    - DOCKER_TAG=build-$TRAVIS_BUILD_NUMBER
    - HELMFILE_IMAGE=quay.io/roboll/helmfile:helm3-v0.94.1

branches:
  only:
    - master

before_script:
  - build/build.sh

script:
  # - deploy/deploy.sh
  - eval $(ssh-agent -s)
  - base64 -d <<<"$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - tar -cvzf - -C ./public . | ssh -v -o StrictHostKeyChecking=no "$SCP_USER@wi1dcard.dev" "tar --no-same-owner -xzf - -C $SCP_DEST"

after_script:
  - docker stop $(docker container ls -q)

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
